export const COUNTRY_CODES = [
  { code: "+1", label: "USA / Canada" },
  { code: "+44", label: "UK" },
  { code: "+91", label: "India" },
  { code: "+86", label: "China" },
  { code: "+81", label: "Japan" },
  { code: "+82", label: "South Korea" },
  { code: "+49", label: "Germany" },
  { code: "+33", label: "France" },
  { code: "+61", label: "Australia" },
  { code: "+55", label: "Brazil" },
  { code: "+52", label: "Mexico" },
  { code: "+234", label: "Nigeria" },
  { code: "+254", label: "Kenya" },
  { code: "+971", label: "UAE" },
  { code: "+966", label: "Saudi Arabia" },
  { code: "+65", label: "Singapore" },
  { code: "+852", label: "Hong Kong" },
  { code: "+886", label: "Taiwan" },
  { code: "+62", label: "Indonesia" },
  { code: "+63", label: "Philippines" },
  { code: "+66", label: "Thailand" },
  { code: "+84", label: "Vietnam" },
  { code: "+90", label: "Turkey" },
  { code: "+48", label: "Poland" },
  { code: "+39", label: "Italy" },
  { code: "+34", label: "Spain" },
  { code: "+31", label: "Netherlands" },
  { code: "+46", label: "Sweden" },
  { code: "+47", label: "Norway" },
  { code: "+45", label: "Denmark" },
  { code: "+41", label: "Switzerland" },
  { code: "+43", label: "Austria" },
  { code: "+32", label: "Belgium" },
  { code: "+353", label: "Ireland" },
  { code: "+64", label: "New Zealand" },
  { code: "+27", label: "South Africa" },
  { code: "+20", label: "Egypt" },
  { code: "+972", label: "Israel" },
  { code: "+7", label: "Russia" },
  { code: "+380", label: "Ukraine" },
  { code: "+57", label: "Colombia" },
  { code: "+56", label: "Chile" },
  { code: "+54", label: "Argentina" },
  { code: "+51", label: "Peru" },
  { code: "+60", label: "Malaysia" },
  { code: "+92", label: "Pakistan" },
  { code: "+880", label: "Bangladesh" },
  { code: "+94", label: "Sri Lanka" },
  { code: "+977", label: "Nepal" },
];
